### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Davoleo** [shadowfacts/ShadowMC#29] opened 2018-01-01 00:07 UTC
Chrash while loading

Steps to reproduce:

- Crash on startup

Link to crash report https://gist.github.com/Davoleo/7f4948508914759e498f684b83750866

ShadowMC version: 3.8.3

Minecraft version: 1.12.2

**Comment by shadowfacts** [comment] 2018-01-01 03:46
Duplicate of #28.

**Closed as completed by shadowfacts** 2018-01-01 03:46 UTC
